#!/usr/bin/env python3 
import os
import argparse
import json
import configparser
import lib.util
import lib.metadata

config = configparser.ConfigParser()

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Save authentication data for 802.1X')
    parser.add_argument('-i', '--info', action='store_true')
    parser.add_argument('-c', '--config', default='/etc/rdma/oracle_rdma.conf')

    args = parser.parse_args()
    config.sections()
    config.read(args.config)

    if not config['DEFAULT']['private_key']:
        raise KeyError("Prive key localtion not found in the configuration file.")

    if not config['DEFAULT']['password']:
        raise KeyError("Private key password not found in the configuration file.")
    
    if not config['DEFAULT']['auto']:
        if not config['DEFAULT']['interfaces']:
            raise KeyError("Interface definitions not found in the configuration file.")


    if args.info: 
        lib.util.check_certificates(config, write=False)
        lib.util.check_configs(config, write=False)
        lib.util.check_units(config, write=False, start=False)
    else: 
        lib.util.check_certificates(config, write=True)
        lib.util.check_configs(config, write=True)
        lib.util.check_units(config, write=True, start=True)
    

    